name: cd

on:
  push:
    branches: ["release"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.17.1
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g yarn@1.22.19
      - run: yarn install --frozen-lockfile
      - run: yarn ci:build
      - run: yarn ci:test
      # - run: |
      #     npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
      #     npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - run: |
          npm config set '//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}'
          npm publish --access public
